
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml

# Telegram Bot
telegram_bot:
  - platform: polling
    api_key: "6169993763:AAHk2gAIm-v2IPPvLP7pwIdCDm0JdZHhwI0"
    allowed_chat_ids:
      - 6165929155

# Notifier
notify:
  - platform: telegram
    name: "HomeAssistantBot"
    chat_id: 6165929155
