esphome:
  name: esp32-device
  friendly_name: ESP32-Device

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "v3X3d7nCOKj9NTcBdz2XfJCyi00fvmk6z9o+OvdevHo="

ota:
  password: "13cd09fb3619383bb209a74ca9e5c4fb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.85
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Device Fallback Hotspot"
    password: "jSI1ixJ8pa5b"

captive_portal:

output:
  - platform: gpio
    pin: 23   # pin number connected to the LED
    id: generator_indicator

switch:
  platform: output
  output: generator_indicator
  name: "ESP32 Switch"
  id: esp32_switch
